sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:

install:
  - ./gradlew assemble
  - docker build -t andrestefanov/dwa .

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: r7cszA9VzpjQHPcxfLZDne6nRlYw/eioF4egVL77YOEoqAeBpvLkG1Ngh6OAl4s04hlScWEICIKNdLlikuMCEMK0z1hkxxUbncXIRS169aPFAX8/SZBN19/tIz1fINHIuCX3wgDHCYGBLavwd9C4CEP/X+LPSEHW//wMm3/UpTnMqS4E6QL4uYqVJlqZqB97g/8RYU20tvrMBG+bUgafoLrkXAD3oIZIqvc2Y5vJpj1js3WWWbpk526QebcLSJlNXLC42CaFBAwBYmfdKxpBPZM1SlpLYQ3nG5J4MMpyhrFS0Yt7HSh0AlBHjFvsUiSJiJwnZB93SKpIbzCTEFIWCoS+kem9TSYW5qf6s6GCE3Gfc3kY5pqLJAzTA46Xaw08EBvXaSOcVOrDZ9Z1rxdcCw/5Cnij1odAwV1uH+tOJtfBebYGj71S4YWdp52oYU5YQhdpZqqCPhkvoyY/rGwh/UE2/jq/IxVNoREvGKxppKsdjuWCKLitTYtfbSwKw7dx9a6kwd+ci5FPFgRnl6xxu8R8uOOfGIJ2zNYuwHOu1ZV/4ICY3gUuIpR+Y5ITpKm4vqj8z/d0/LDd5fIfPCWdKChDKuDZ6FS4gO3wEH3OmC/JeBTjfqvYCDchyP91hPhfHeefpgJB2UnodRfLpUDx3vaB0EY7Yzs0vUuVuor4CVU=
  file: build/libs/dwa.jar
  on:
    tags: true

after_success:
  - docker login -u andrestefanov -p "$DOCKER_PASSWORD";
  - docker push andrestefanov/dwa;